### ISSUE TITLE
IPA reference chapter incorrect link

### ISSUE THREAD

**Issue by musicnerd** [humdrum-tools/humdrum-documentation#18]
In Ch.27 it says "Discussion of the IPA representation will be delayed until [Chapter 34.](https://www.humdrum.org/guide/ch34)" but it's actually chapter 33. Link needs to be updated.

**Comment by craigsapp** [comment]
Fixed with commit https://github.com/humdrum-tools/humdrum-documentation/commit/af155a315f671305f2d25ef92fd1bd77b9b625d9

And archived page of the c. 2002 online manual:
https://github.com/humdrum-tools/humdrum-documentation/commit/b211a41695c4eb420b334566a16236d91f75cda4
